version: '3.6'

networks:
  global:
    external: true

volumes:
  mongo-data:

services:

  mongo:
    container_name: mongo
    image: mongo:3.6.4
    ports:
      - 27020:27017/tcp
    volumes:
      - mongo-data:/data/db
    networks:
      global:
        aliases:
          - common-mongo

  backend:
    depends_on:
      - mongo
    image: deniskublitskiy/hcs-challenge-backend:develop
    build: ../
    ports:
      - 3333:5000
    command: npm run seeds
    environment:
      MONGO_URI: mongodb://mongo/hcs-test
      NODE_ENV: development
      SERVICE_PORT: 5000
      TOKEN_EXPIRY: 7d
    networks:
      - global